[tool.poetry]
name = "codespace-algorand"
version = "0.1.0"
description = ""
authors = ["JuliaBubble1 <jvchan@alum.mit.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
