[tool.poetry]
name = "my-codespace-algorand"
version = "0.1.0"
description = ""
authors = ["Safwan Ahmad  <sahmedsaffi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
